export const mockDocumentData = [
    {
        id: "1",
        name: "Commercial License.pdf",
        category: "Licensing",
        description: "Official business license issued by ADGM Registration Authority",
        fileType: "pdf",
        fileSize: "1.5 MB",
        uploadDate: "2023-12-31",
        expiryDate: "2024-12-31",
        uploadedBy: "John Smith",
        status: "Active",
        tags: ["license", "registration", "legal"],
        isConfidential: false,
        fileUrl: "https://example.com/files/commercial-license.pdf",
        versions: [
            {
                versionNumber: 1,
                uploadDate: "2022-12-31",
                uploadedBy: "John Smith",
                notes: "Initial upload",
                fileUrl: "https://example.com/files/commercial-license-v1.pdf"
            }
        ]
    },
    {
        id: "2",
        name: "Articles of Association.pdf",
        category: "Legal",
        description: "Company's articles of association document",
        fileType: "pdf",
        fileSize: "2.4 MB",
        uploadDate: "2010-03-15",
        expiryDate: null,
        uploadedBy: "Sarah Johnson",
        status: "Active",
        tags: ["legal", "governance", "incorporation"],
        isConfidential: true,
        fileUrl: "https://example.com/files/articles-of-association.pdf",
        versions: []
    },
    {
        id: "3",
        name: "Software Provider License.pdf",
        category: "Licensing",
        description: "License for providing software services",
        fileType: "pdf",
        fileSize: "1.2 MB",
        uploadDate: "2022-07-15",
        expiryDate: "2024-07-15",
        uploadedBy: "John Smith",
        status: "Active",
        tags: ["license", "software", "TRA"],
        isConfidential: false,
        fileUrl: "https://example.com/files/software-provider-license.pdf",
        versions: []
    },
    {
        id: "4",
        name: "ISO 27001 Certificate.pdf",
        category: "Certifications",
        description: "Information Security Management certification",
        fileType: "pdf",
        fileSize: "1.2 MB",
        uploadDate: "2022-06-15",
        expiryDate: "2024-06-15",
        uploadedBy: "Fatima Al Zaabi",
        status: "Active",
        tags: ["certification", "security", "ISO"],
        isConfidential: false,
        fileUrl: "https://example.com/files/iso-27001-certificate.pdf",
        versions: []
    },
    {
        id: "5",
        name: "Data Protection Registration.pdf",
        category: "Compliance",
        description: "Data protection registration certificate",
        fileType: "pdf",
        fileSize: "1.5 MB",
        uploadDate: "2023-01-10",
        expiryDate: "2024-01-10",
        uploadedBy: "Mohammed Hassan",
        status: "Expired",
        tags: ["compliance", "data protection", "privacy"],
        isConfidential: false,
        fileUrl: "https://example.com/files/data-protection-registration.pdf",
        versions: []
    },
    {
        id: "6",
        name: "UAE Innovation Award Certificate.jpg",
        category: "Certifications",
        description: "Award certificate for innovation excellence",
        fileType: "image",
        fileSize: "1.8 MB",
        uploadDate: "2022-12-15",
        expiryDate: null,
        uploadedBy: "Sarah Johnson",
        status: "Active",
        tags: ["award", "innovation", "recognition"],
        isConfidential: false,
        fileUrl: "https://example.com/files/innovation-award.jpg",
        versions: []
    },
    {
        id: "7",
        name: "Board Resolution - 2023.pdf",
        category: "Legal",
        description: "Board resolution approving annual strategy",
        fileType: "pdf",
        fileSize: "1.1 MB",
        uploadDate: "2023-01-10",
        expiryDate: null,
        uploadedBy: "John Smith",
        status: "Active",
        tags: ["governance", "board", "resolution"],
        isConfidential: true,
        fileUrl: "https://example.com/files/board-resolution-2023.pdf",
        versions: []
    },
    {
        id: "8",
        name: "Insurance Policy.pdf",
        category: "Insurance",
        description: "Company liability insurance policy",
        fileType: "pdf",
        fileSize: "3.2 MB",
        uploadDate: "2023-05-20",
        expiryDate: "2024-05-20",
        uploadedBy: "Ahmed Al Mansoori",
        status: "Active",
        tags: ["insurance", "liability", "policy"],
        isConfidential: false,
        fileUrl: "https://example.com/files/insurance-policy.pdf",
        versions: [
            {
                versionNumber: 1,
                uploadDate: "2022-05-20",
                uploadedBy: "Ahmed Al Mansoori",
                notes: "Initial policy",
                fileUrl: "https://example.com/files/insurance-policy-v1.pdf"
            }
        ]
    },
    {
        id: "9",
        name: "Office Lease Agreement.pdf",
        category: "Facilities",
        description: "Lease agreement for headquarters office space",
        fileType: "pdf",
        fileSize: "4.5 MB",
        uploadDate: "2018-06-15",
        expiryDate: "2028-06-15",
        uploadedBy: "Sarah Johnson",
        status: "Active",
        tags: ["lease", "facility", "contract"],
        isConfidential: true,
        fileUrl: "https://example.com/files/lease-agreement.pdf",
        versions: []
    },
    {
        id: "10",
        name: "Tax Registration Certificate.pdf",
        category: "Tax",
        description: "Tax registration certificate from Federal Tax Authority",
        fileType: "pdf",
        fileSize: "950 KB",
        uploadDate: "2018-01-01",
        expiryDate: null,
        uploadedBy: "Ahmed Al Mansoori",
        status: "Active",
        tags: ["tax", "registration", "FTA"],
        isConfidential: false,
        fileUrl: "https://example.com/files/tax-registration.pdf",
        versions: []
    },
    {
        id: "11",
        name: "Employee Handbook.pdf",
        category: "HR",
        description: "Company policies and procedures for employees",
        fileType: "pdf",
        fileSize: "5.8 MB",
        uploadDate: "2023-03-01",
        expiryDate: null,
        uploadedBy: "Sarah Johnson",
        status: "Active",
        tags: ["HR", "policies", "employees"],
        isConfidential: false,
        fileUrl: "https://example.com/files/employee-handbook.pdf",
        versions: [
            {
                versionNumber: 2,
                uploadDate: "2022-01-15",
                uploadedBy: "Sarah Johnson",
                notes: "Updated policies",
                fileUrl: "https://example.com/files/employee-handbook-v2.pdf"
            },
            {
                versionNumber: 1,
                uploadDate: "2021-02-10",
                uploadedBy: "Sarah Johnson",
                notes: "Initial version",
                fileUrl: "https://example.com/files/employee-handbook-v1.pdf"
            }
        ]
    },
    {
        id: "12",
        name: "Data Center Operations License.pdf",
        category: "Licensing",
        description: "License for operating data center facilities",
        fileType: "pdf",
        fileSize: "980 KB",
        uploadDate: "2022-08-20",
        expiryDate: "2024-01-25",
        uploadedBy: "Fatima Al Zaabi",
        status: "Pending Renewal",
        tags: ["license", "data center", "operations"],
        isConfidential: false,
        fileUrl: "https://example.com/files/data-center-license.pdf",
        versions: []
    }
];